### ISSUE TITLE
[BUG] Wrong map type shown in vote

### ISSUE THREAD

**Issue by tslashd** [surftimer/SurfTimer-Mapchooser#5]
**Describe the bug**
Map vote shows map as a staged map when in fact it's a Linear.

**surf_dynasty**

**Error Log**
None.

**Expected behavior**
Show the map as a **Linear**
[Link to map from server](https://clarityeu.com/dashboard/map/surf_dynasty)

**Screenshots**
![image](https://user-images.githubusercontent.com/74899888/186671465-4cd48a1b-b748-4665-a893-be6943b83c01.png)
![image](https://user-images.githubusercontent.com/74899888/186672997-98eefa24-3ded-45b0-b66d-5b21ef2ac3e3.png)

**System Information:**
 - OS: Ubuntu 20.04
 - Mapchooser Version: 2.0.0

**Comment by tslashd** [comment]
Still a thing on **2.0.2**

**Comment by 1zc** [comment]
It just needs some better queries - I should hopefully have some more free time soon to take a look and write some new ones, but if anyone else wants to take a crack at this, feel free

**Comment by 1zc** [comment]
https://github.com/surftimer/SurfTimer-Mapchooser/pull/14
